### ISSUE TITLE
Adding 0-length rows API unclear.

### ISSUE THREAD

**Issue by Bam4d** [entity-neural-network/ragged-buffer#2]
The method for adding a 0-length row (as specified in the README) throws an error:
```
ragged_buffer = RaggedBufferF32(3)

ragged_buffer.push(np.array([[0,0,0],[1,1,1]], np.float32))
ragged_buffer.push(np.array([[]], np.float32)) <- ERROR thrown here
```

Whereas specifying the `reshape(0,3)` allows the array to be pushed:
```
ragged_buffer = RaggedBufferF32(3)

ragged_buffer.push(np.array([[0,0,0],[1,1,1]], np.float32))
ragged_buffer.push(np.array([[]], np.float32).reshape(0,3))
                                              ^^^^^^^^^^^^
```

If we push a 0-length array to the ragged buffer I think internally the `reshape` operation should be assumed?

**Comment by cswinter** [comment]
Reproduction:

```python
>>> import numpy as np
>>> import ragged_buffer
>>> rb = ragged_buffer.RaggedBufferF32(3)
>>> rb.push(np.array([[0,0,0],[1,1,1]], np.float32))
>>> rb.push(np.array([[]], np.float32))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Features mismatch: 3 != 0
>>> rb.push(np.array([], np.float32))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: argument 'items': Shape Mismatch:
 from=(dim=1, dtype=Float32), to=(dim=2, dtype=Float32)
>>> rb.push(np.array([], np.float32).reshape(0, 3))
```

I'm not sure we should allow `rb.push(np.array([[]], np.float32))`. [[]] is a list with one zero-length item, rather than an empty list. The error message seems decent, though probably it can be improved (I'm open to suggestions).

The case for allowing `rb.push(np.array([], np.float32))`  is quite good, and indeed the example in the README is currently broken.

**Comment by cswinter** [comment]
Support for `rb.push(np.array([], np.float32))` added in https://github.com/entity-neural-network/ragged-buffer/commit/f629a75621786e6e0b93d99d74943a4eafd90732 and published in 0.2.11 release. Additionally, I've added a `push_empty()` method.

**Comment by Bam4d** [comment]
Not sure if there is a use case for this yet... but i can envisage a scenario where you might want to do soemthing like:
```
ragged_buffer.push(np.array([[],[],[]], np.float32))
ragged_buffer.push(np.array([[1,2,3]], np.float32))
```
where you push specifically 3 zero length rows before pushing a normal row.

Would this be  the equivalent of:
```
ragged_buffer.push(np.array([], np.float32))
ragged_buffer.push(np.array([], np.float32))
ragged_buffer.push(np.array([], np.float32))
ragged_buffer.push(np.array([[1,2,3]], np.float32))
```

?

**Comment by cswinter** [comment]
Yes, `ragged_buffer.push` always pushes a single row, so I don't think we'd want to make an exception for when pushing empty rows.

The `extend` method allows extending with multiple rows, in that case, the input argument is another `RaggedBuffer`. We could consider a version of extend that takes a flattened numpy array and a list of lengths as arguments, similar to `from_flattened`.

**Comment by Bam4d** [comment]
Got it. Thanks for the clarification.
